name: Calculator

on:
    push:
        paths:
            - 'calculator/**'
        branches: [ main, streams ]
    pull_request:
        paths:
            - 'calculator/**'
        branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Run Tests
      id: test
      continue-on-error: true
      run: |
        cd calculator
        cargo install cargo2junit
        cargo test -- -Z unstable-options --format json --report-time | cargo2junit > test_report.xml

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: calculator/test_report.xml