name: Interpreter

on:
    push:
        paths:
            - 'interpreter/**'
            - '.github/workflows/interpreter.yml'
    pull_request:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11  # Specify the Python version you need

    - name: Install dependencies
      run: pip install -r interpreter/requirements.txt  # Adjust this command based on your project

    - name: Run pytest with coverage
      run: |
        coverage run -m pytest
        coverage report -m
        coverage html

    - name: Archive coverage artifacts
      uses: actions/upload-artifact@v3
      with:
        name: coverage-artifacts
        path: |
          .coverage
          htmlcov
